#!/usr/bin/env bash
export PATH=$PATH:/usr/local/cuda/bin
export CUDA_INSTALL_PATH=/usr/local/cuda
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
export OUTPUT=1

cd $1
source setup_environment

cd $2
ldd backprop_cuda

valgrind --tool=massif ./backprop_cuda $3
mv massif.out.* /injector/results/
mv output.* /injector/results
rm backprop_cuda.sm_*
rm config_turing_islip.icnt
rm gpgpu*
rm _*
rm -rf checkpoints/
