#!/usr/bin/env bash
export PATH=$PATH:/usr/local/cuda/bin
export CUDA_INSTALL_PATH=/usr/local/cuda
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
export OUTPUT=1

cd $1
source setup_environment

cd $2
ldd backprop_cuda

./backprop_cuda $3
if [ -f $2/output.dat ]
then
    DIFF=$(diff output.dat output_gpu.dat) 
    if [ "$DIFF" ] 
    then
        diff --suppress-common-lines output.dat output_gpu.dat > diff.txt
        mv diff.txt /injector/results
        echo "WARNING: SDC"
    else
        echo "INFO: MASKED"
    fi
else
    echo "ERROR: DUE"
fi
rm backprop_cuda.sm_*
rm config_*
rm gpgpu*
rm _*
rm -rf checkpoints/
