#!/usr/bin/env bash
export PATH=$PATH:/usr/local/cuda/bin
export CUDA_INSTALL_PATH=/usr/local/cuda
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

cd $1
source setup_environment

cd $2
ldd nn

./nn $3 -r 5 -lat 30 -lng 90
rm nn.sm_75.ptx*
rm _app_cuda_version_*
rm _cuobjdump_list_ptx_*
rm -rf checkpoints/
