#!/usr/bin/env bash
export PATH=$PATH:/usr/local/cuda/bin
export CUDA_INSTALL_PATH=/usr/local/cuda
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
export OUTPUT=1

cd $1
source setup_environment

cd $2
ldd lavaMD

valgrind --tool=massif ./lavaMD -boxes1d $3
mv massif.out.* /injector/results/
mv output.* /injector/results
rm lavaMD.sm_*
rm config_*
rm gpgpu*
rm _*
rm -rf checkpoints/
