#!/usr/bin/env bash
export PATH=$PATH:/usr/local/cuda/bin
export CUDA_INSTALL_PATH=/usr/local/cuda
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
export OUTPUT=1

cd $1
source setup_environment

cd $2
ldd gaussian

#./gaussian -f ../../data/gaussian/matrix4.txt
valgrind --tool=massif ./gaussian -s $3
DIFF=$(diff output.txt output_gpu.txt) 
if [ "$DIFF" ] 
then
    diff --suppress-common-lines output.txt output_gpu.txt > diff.txt
    mv diff.txt /injector/results
    echo "WARNING: SDC"
else
    echo "INFO: MASKED"
fi
mv massif.out.* /injector/results/
mv output.* /injector/results
rm gaussian.sm_*
rm config_*
rm gpgpu*
rm _*
rm -rf checkpoints/
