#!/usr/bin/env bash
export PATH=$PATH:/usr/local/cuda/bin
export CUDA_INSTALL_PATH=/usr/local/cuda
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

cd $1
source setup_environment

cd $2
ldd gaussian

#./gaussian -f ../../data/gaussian/matrix4.txt
./gaussian -s $3
