#!/usr/bin/env bash
export PATH=$PATH:/usr/local/cuda/bin
export CUDA_INSTALL_PATH=/usr/local/cuda
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

cd $1
source setup_environment

cd $2
ldd lud

valgrind --tool=massif ./lud -s $3
rm lud.sm_*
rm config_*
rm gpgpu*
rm _*
rm -rf checkpoints/
